/*
    This file has been generated by bvtidl.pl. DO NOT MODIFY!
*/
#ifndef __BVTERROR_H__
#define __BVTERROR_H__

#include <bvt_c/bvt_retval.h>

#ifndef DOXY_IGNORE
#ifdef _WIN32
#	ifdef BUILDING_BVTSDK
#		define BVTSDK_EXPORT __declspec(dllexport)
#	else
#		define BVTSDK_EXPORT __declspec(dllimport)
#	endif
#else
#	define BVTSDK_EXPORT
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

/** \file
 * \defgroup BVTError BVTError Object
 * The Error object provides access to the SDKs error reporting 
 * system.  This allows the user to map from an error number to 
 * a human readable description of the error.
 * @{
*/

/** Return a description of the error
 * \param code Error code 
 */
BVTSDK_EXPORT char* BVTError_GetString(RetVal code);

/** Return a string version of the name of the error constant.
 * \param code Error code 
 */
BVTSDK_EXPORT char* BVTError_GetName(RetVal code);

/** @}*/

#ifdef __cplusplus
}
#endif

#endif
