/*
    This file has been generated by bvtidl.pl. DO NOT MODIFY!
*/
#ifndef __BVTSDK_H__
#define __BVTSDK_H__

#include <bvt_c/bvt_retval.h>

#ifndef DOXY_IGNORE
#ifdef _WIN32
#	ifdef BUILDING_BVTSDK
#		define BVTSDK_EXPORT __declspec(dllexport)
#	else
#		define BVTSDK_EXPORT __declspec(dllimport)
#	endif
#else
#	define BVTSDK_EXPORT
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

/** Return the major version number of the SDK.
 */
BVTSDK_EXPORT int BVTSDK_MajorVersion();

/** Return the minor version of the SDK.
 */
BVTSDK_EXPORT int BVTSDK_MinorVersion();

/** Return the build number of the SDK.
 */
BVTSDK_EXPORT int BVTSDK_BuildNumber();

/** @}*/

#ifdef __cplusplus
}
#endif

#endif
