/*
    This file has been generated by bvtidl.pl. DO NOT MODIFY!
*/
#ifndef __CPP_BVTSDK_H__
#define __CPP_BVTSDK_H__

#include <string>
#include <bvt_cpp/bvt_retval.h>

namespace BVTSDK
{


class SDK
{
public:
	/** Return the major version number of the SDK.
	 */
	static int MajorVersion()
	{
		return BVTSDK_MajorVersion(  );
	}

	/** Return the minor version of the SDK.
	 */
	static int MinorVersion()
	{
		return BVTSDK_MinorVersion(  );
	}

	/** Return the build number of the SDK.
	 */
	static int BuildNumber()
	{
		return BVTSDK_BuildNumber(  );
	}


};
}

#endif
